data<-read.table("../exdata-data-household_power_consumption/household_power_consumption.txt",sep=";",header=TRUE,na.strings = "?")
data<-subset(data,data$Date == "1/2/2007" | data$Date == "2/2/2007")
x<-strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
par(mfrow = c(2,2),mar = c(4, 4, 2, 1))
plot(x,data$Global_active_power,ylab = "Global Active Power",xlab = "",type = "l")
plot(x,data$Voltage,ylab = "Voltage",xlab = "datetime",type = "l")
plot(x,data$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy sub metering")
lines(x,data$Sub_metering_2,col="red")
lines(x,data$Sub_metering_3,col="blue")
legend("topright",cex=0.5,bty = 'n',inset=c(0,0), lty=c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(x,data$Global_reactive_power,ylab = "Global_reactive_power",xlab = "datetime",type = "l")
dev.copy(png, file = "plot4.png")
dev.off()