data<-read.table("../exdata-data-household_power_consumption/household_power_consumption.txt",sep=";",header=TRUE,na.strings = "?")
data<-subset(data,data$Date == "1/2/2007" | data$Date == "2/2/2007")
x<-strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
plot(x,data$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy sub metering")
lines(x,data$Sub_metering_2,col="red")
lines(x,data$Sub_metering_3,col="blue")
legend("topright", lty=c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()